import type { City, District, NewsItem } from "./types";

export const FALLBACK_TOP_CITIES: City[] = [
  { id: "ahm", name: "Ahmedabad", type: "District", label: "Current", badges: ["Smart City"] },
  { id: "sur", name: "Surat", type: "District", label: "Current", badges: ["Diamond Hub"] },
  { id: "vad", name: "Vadodara", type: "District", label: "Current", badges: ["Education"] },
  { id: "raj", name: "Rajkot", type: "District", label: "Current", badges: ["Industrial"] },
  { id: "bvn", name: "Bhavnagar", type: "District", label: "Current", badges: ["Coastal"] },
  { id: "jmn", name: "Jamnagar", type: "District", label: "Current", badges: ["Refinery"] },
  { id: "jnd", name: "Junagadh", type: "District", label: "Current", badges: ["Tourism"] },
  { id: "gnd", name: "Gandhinagar", type: "District", label: "Current", badges: ["Capital"] },
  { id: "nvs", name: "Navsari", type: "District", label: "New", badges: ["Agri"] },
  { id: "gdh", name: "Gandhidham", type: "City", label: "Approved", badges: ["Port"] },
  { id: "mrb", name: "Morbi", type: "District", label: "Approved", badges: ["Ceramics"] },
  { id: "vpi", name: "Vapi", type: "City", label: "New", badges: ["Industrial"] },
];

export const FALLBACK_DISTRICTS: District[] = [
  "Ahmedabad",
  "Amreli",
  "Anand",
  "Aravalli",
  "Banaskantha",
  "Bharuch",
  "Bhavnagar",
  "Botad",
  "Chhota Udaipur",
  "Dahod",
  "Dang",
  "Devbhoomi Dwarka",
  "Gandhinagar",
  "Gir Somnath",
  "Jamnagar",
  "Junagadh",
  "Kheda",
  "Kutch",
  "Mahisagar",
  "Mehsana",
  "Morbi",
  "Narmada",
  "Navsari",
  "Panchmahal",
  "Patan",
  "Porbandar",
  "Rajkot",
  "Sabarkantha",
  "Surat",
  "Surendranagar",
  "Tapi",
  "Vadodara",
  "Valsad",
].map((n, i) => ({ id: `dist-${i}`, name: n }));

export const FALLBACK_NEWS: NewsItem[] = [
  {
    id: "1",
    title: "Ahmedabad Metro Phase-2 completes key bridge work",
    source: "NewsPulse",
    category: "Development",
    district: "Ahmedabad",
    summary: "Construction crosses Sabarmati; trial runs planned next month.",
    // Use a fixed timestamp to avoid SSR/CSR mismatch
    publishedAt: "2025-11-01T10:00:00.000Z",
  },
  {
    id: "2",
    title: "Surat reports strong monsoon preparedness",
    source: "Civic",
    category: "Civic",
    district: "Surat",
    summary: "Stormwater drains cleaned across 7 zones; control rooms active.",
    publishedAt: "2025-11-01T08:30:00.000Z",
  },
  {
    id: "3",
    title: "Junagadh tourism push for Gir safari off-season",
    source: "Tourism",
    category: "Culture",
    district: "Junagadh",
    summary: "Eco-trails and heritage walks to drive local economy.",
    publishedAt: "2025-11-01T07:15:00.000Z",
  },
];
